### ISSUE TITLE
GitHub Readme Stats is not displayed completely in the screenshots

### ISSUE THREAD

**Issue by ouuan** [zzetao/awesome-github-profile-data#1]
[GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats) is not displayed completely in the screenshots.

For example:

-   [![ouuan](https://raw.githubusercontent.com/zzetao/awesome-github-profile-data/master/screenshots/ouuan.jpeg)](https://github.com/ouuan)

-   [![moepoi](https://raw.githubusercontent.com/zzetao/awesome-github-profile-data/master/screenshots/moepoi.jpeg)](https://github.com/moepoi)

**Comment by zzetao** [comment]
Thanks, it's fixed.
